name: app
description: Flutter Bloc Playground
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.2                                        # https://pub.dev/packages/flutter_bloc
  get_it: ^7.2.0                                              # https://pub.dev/packages/get_it
  go_router: 6.2.0                                            # https://pub.dev/packages/go_router

  dio: 5.0.2                                                  # https://pub.dev/packages/dio

  logger: ^1.3.0                                              # https://pub.dev/packages/logger
  permission_handler: ^10.2.0                                 # https://pub.dev/packages/permission_handler
  device_info_plus: ^8.1.0                                    # https://pub.dev/packages/device_info_plus
  package_info_plus: ^3.0.3                                   # https://pub.dev/packages/package_info_plus
  intl: ^0.18.0                                               # https://pub.dev/packages/intl

  carousel_slider: ^4.2.1                                     # https://pub.dev/packages/carousel_slider
  fluttertoast: ^8.2.1                                        # https://pub.dev/packages/fluttertoast
  cached_network_image: ^3.2.3                                # https://pub.dev/packages/cached_network_image
  image_picker: ^0.8.7                                        # https://pub.dev/packages/image_picker

  freezed_annotation: ^2.2.0                                  # https://pub.dev/packages/freezed_annotation
  json_annotation: ^4.8.0                                     # https://pub.dev/packages/json_annotation
  equatable: ^2.0.5                                           # https://pub.dev/packages/equatable

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  bloc_test: ^9.1.1                                           # https://pub.dev/packages/bloc_test
  freezed: ^2.3.2                                             # https://pub.dev/packages/freezed
  build_runner: ^2.3.3                                        # https://pub.dev/packages/build_runner
  json_serializable: ^6.6.1                                   # https://pub.dev/packages/json_serializable

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
